-- =====================================================================
-- pg-ncmu init-db (extensions only; tables owned by alembic from Phase 1)
-- =====================================================================
-- Source : NCMU-Wiki/sources/specs/ncmu-dify-design-v3.md §14.3
--          (lines 1302-1360, full DDL transcribed verbatim).
-- Owner  : ncmu_app  (POSTGRES_USER from .env).
-- Database: ncmu     (POSTGRES_DB from .env, pre-created by entrypoint).
--
-- The postgres official image runs scripts in /docker-entrypoint-initdb.d/
-- AFTER the POSTGRES_DB has been created and connected to. Therefore this
-- script does NOT issue `CREATE DATABASE ncmu` (would fail with
-- "database already exists"); it operates inside the `ncmu` database.
--
-- Idempotency: re-running the entrypoint on a populated data dir is a
-- no-op (postgres skips initdb), so this script never executes a second
-- time on the same volume. Statements use IF NOT EXISTS where supported
-- to make manual re-runs (psql -f) safe as well.
--
-- DEPLOY-1 修订（2026-04-25）：
--   v3.3.1 baseline 中含 dify_apps + dify_external_kb_configs +
--   dify_app_kb_bindings 3 张表 CREATE，Phase 1 起改由 alembic 0002/0003
--   独占建表（按 errata-08 schema），本文件不再 CREATE 这 3 张表。
--   保留 pg_trgm extension（Phase 1 alembic 0002 的 dify_apps_name_trgm
--   GIN 索引仍依赖它；放在 init-db 比放在迁移里更可靠，避免每次
--   `CREATE EXTENSION` 需要 superuser 权限的麻烦）。
-- =====================================================================


-- =====================================================================
-- Extension: pg_trgm (trigram similarity for dify_apps name search)
-- =====================================================================
-- Required by Phase 1 alembic 0002 dify_apps_name_trgm GIN index;
-- admin panel uses ILIKE / similarity() for App search by Chinese name.
-- Created here (as the postgres superuser entrypoint runs initdb scripts)
-- so the alembic migration — running as ncmu_app — does not need the
-- CREATEROLE / superuser bit.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
