"""StorageBackend abstraction + LocalFsBackend (Phase 2C Q1-C).

Backends are kept behind a ``Protocol`` so a future MinIO backend can be
swapped in via DI without changing the routes/admin code. ``LocalFsBackend``
is the only concrete impl today; the MinIO seam is marked with a TODO at
the bottom so reviewers can grep ``MinioBackend`` to find it.

Layout on disk::

    <storage_root>/<application_id>/<file_id>_<original_filename>

The directory tree is created lazily on ``save`` (``mkdir(parents=True,
exist_ok=True)``) so a fresh deploy doesn't need a pre-existing
``personal-kb`` directory.

Concurrency:
- ``save`` does NOT take a lock — each ``(application_id, file_id)`` pair
  is unique by construction (file_id is a UUID generated by the caller),
  so two save() calls cannot collide on the same path.
- File I/O runs through ``asyncio.to_thread`` so the writes don't block
  the event loop on slow disks (no aiofiles dep — that would require a
  pyproject.toml change which is out-of-scope for PC2-A).
"""
from __future__ import annotations

import asyncio
from dataclasses import dataclass
from pathlib import Path
from typing import AsyncIterator, Protocol, runtime_checkable
from uuid import UUID


@dataclass(frozen=True)
class StorageRef:
    """Opaque reference to a stored blob — what the DB row persists.

    ``backend`` lets a future deploy mix LocalFs + MinIO rows in the same
    table (admin gradually migrates archives); for now every row carries
    ``backend='localfs'``.
    """

    backend: str
    path: str


@runtime_checkable
class StorageBackend(Protocol):
    """Protocol the routes/admin layer programs against."""

    async def save(
        self,
        application_id: UUID,
        file_id: UUID,
        original_filename: str,
        chunks: AsyncIterator[bytes],
    ) -> StorageRef:
        """Persist a stream of bytes; return where it landed.

        Implementations MUST consume ``chunks`` lazily — the multipart
        layer hands us an async iterator so 50 MB uploads don't sit in
        RAM.
        """

    def open(self, ref: StorageRef) -> AsyncIterator[bytes]:
        """Stream the stored bytes back (admin download path).

        Returns an async iterator the caller awaits-over. ``open`` itself
        is sync — opening a file descriptor doesn't need the event loop.
        Raises ``FileNotFoundError`` if the backing blob is gone.
        """

    async def delete(self, ref: StorageRef) -> None:
        """Remove the underlying blob — best-effort, idempotent."""


class LocalFsBackend:
    """Local-filesystem implementation of :class:`StorageBackend`.

    ``storage_root`` is injected at construction time so production reads
    it from the operator's env (``PERSONAL_KB_STORAGE_ROOT``, wired by
    TASK-PC2-D) and tests use ``tmp_path``.
    """

    BACKEND_NAME = "localfs"
    READ_CHUNK_SIZE = 8192

    def __init__(self, storage_root: Path | str):
        self._root = Path(storage_root)

    def _path_for(
        self,
        application_id: UUID,
        file_id: UUID,
        original_filename: str,
    ) -> Path:
        # Defensive: drop any directory parts a malicious filename might
        # carry (``../../etc/passwd`` → ``passwd``). The filename is also
        # length-bounded by the DB column (255).
        safe_name = Path(original_filename).name
        return self._root / str(application_id) / f"{file_id}_{safe_name}"

    async def save(
        self,
        application_id: UUID,
        file_id: UUID,
        original_filename: str,
        chunks: AsyncIterator[bytes],
    ) -> StorageRef:
        target = self._path_for(application_id, file_id, original_filename)
        await asyncio.to_thread(
            target.parent.mkdir, parents=True, exist_ok=True
        )

        def _open_for_write():
            return target.open("wb")

        fh = await asyncio.to_thread(_open_for_write)
        try:
            async for chunk in chunks:
                if chunk:
                    await asyncio.to_thread(fh.write, chunk)
        finally:
            await asyncio.to_thread(fh.close)
        return StorageRef(backend=self.BACKEND_NAME, path=str(target))

    def open(self, ref: StorageRef) -> AsyncIterator[bytes]:
        path = Path(ref.path)
        if not path.exists():
            raise FileNotFoundError(ref.path)

        async def _stream() -> AsyncIterator[bytes]:
            fh = await asyncio.to_thread(path.open, "rb")
            try:
                while True:
                    chunk = await asyncio.to_thread(
                        fh.read, self.READ_CHUNK_SIZE
                    )
                    if not chunk:
                        break
                    yield chunk
            finally:
                await asyncio.to_thread(fh.close)

        return _stream()

    async def delete(self, ref: StorageRef) -> None:
        path = Path(ref.path)
        if path.exists():
            await asyncio.to_thread(path.unlink)


# TODO(Phase later): class MinioBackend(StorageBackend): ...
# When NCMU outgrows single-node local fs, drop a MinIO impl here and
# inject it instead — routes/admin code stays untouched thanks to the
# Protocol.
